"use strict";
exports.__esModule = true;
exports.useDeleteImage = exports.useCreateUploadMultiFiles = exports.useGetProvincesPrices = exports.useCreateRequest = exports.useCreateShipment = exports.useGetOneShipments = exports.useGetAllShipments = exports.useCreateChangeMultiStatus = exports.useGetMultipleShipments = exports.useUpdateShipment = exports.useGetAllPickupShipments = exports.useUpdatePickupGroup = void 0;
var useGetAllShipments_1 = require("./useGetAllShipments");
exports.useGetAllShipments = useGetAllShipments_1["default"];
var useGetOneShipments_1 = require("./useGetOneShipments");
exports.useGetOneShipments = useGetOneShipments_1["default"];
var useCreateShipment_1 = require("./useCreateShipment");
exports.useCreateShipment = useCreateShipment_1["default"];
var useCreateRequest_1 = require("./useCreateRequest");
exports.useCreateRequest = useCreateRequest_1["default"];
var useGetProvincesPrices_1 = require("./useGetProvincesPrices");
exports.useGetProvincesPrices = useGetProvincesPrices_1["default"];
var useCreateChangeMultiStatus_1 = require("./useCreateChangeMultiStatus");
exports.useCreateChangeMultiStatus = useCreateChangeMultiStatus_1["default"];
var useGetMultipleShipments_1 = require("./useGetMultipleShipments");
exports.useGetMultipleShipments = useGetMultipleShipments_1["default"];
var useUpdateShipment_1 = require("./useUpdateShipment");
exports.useUpdateShipment = useUpdateShipment_1["default"];
var useGetAllPickupShipments_1 = require("./useGetAllPickupShipments");
exports.useGetAllPickupShipments = useGetAllPickupShipments_1["default"];
var useUpdatePickupGroup_1 = require("./useUpdatePickupGroup");
exports.useUpdatePickupGroup = useUpdatePickupGroup_1["default"];
var useCreateUploadMultiFiles_1 = require("./useCreateUploadMultiFiles");
exports.useCreateUploadMultiFiles = useCreateUploadMultiFiles_1["default"];
var useDeleteImage_1 = require("./useDeleteImage");
exports.useDeleteImage = useDeleteImage_1["default"];
